### ISSUE TITLE
Exhaustive conditions

### ISSUE THREAD

**Issue by rareyesdev** [rareyesdev/blog#2]
In the scenario in which we need to do some conditional logic based on a discriminant value we see code like this:

> `calculateRideFare`, `calculateDeliveryFare`, and `calculateDeliveryFare2` are just fake methods that simulate that we are doing different things on each branch.

### Option 1: Uses else clause

```typescript
const calculateFare1 = (product: Product) => {
    if (product.type === 'RIDE') {
        const rideFare = 0; // API call to get the fare.
        return calculateRideFare(product, rideFare);
    } else if (product.type === 'FOOD_DELIVERY') {
        const deliveryFare = 0; // API call to get the fare.
        return calculateDeliveryFare(product, deliveryFare);
    } else {
        const deliveryFare = 0; // API call to get the fare.
        return calculateDeliveryFare2(product, deliveryFare);
    }
};
```

### Option 2: Uses only IF statements and throws.

```typescript
const calculateFare2 = (product: Product) => {
    if (product.type === 'RIDE') {
        const rideFare = 0; // API call to get the fare.
        return calculateRideFare(product, rideFare);
    } else if (product.type === 'FOOD_DELIVERY') {
        const deliveryFare = 0; // API call to get the fare.
        return calculateDeliveryFare(product, deliveryFare);
    } else if (product.type === 'ITEM_DELIVERY') {
        const deliveryFare = 0; // API call to get the fare.
        return calculateDeliveryFare2(product, deliveryFare);
    }

    throw new Error(`Unhandled product type ${product.type}`);
};
```

### Option 3: Uses a switch and improves readability.

```typescript
const calculateFare3 = (product: Product) => {
    switch (product.type) {
        case 'RIDE': {
            const rideFare = 0; // API call to get the fare.
            return calculateRideFare(product, rideFare);
        }
        case 'FOOD_DELIVERY': {
            const deliveryFare = 0; // API call to get the fare.
            return calculateDeliveryFare(product, deliveryFare);    
        }
        case 'ITEM_DELIVERY': {
            const deliveryFare = 0; // API call to get the fare.
            return calculateDeliveryFare2(product, deliveryFare);            
        }
        default:
            throw new Error(`Unhandled product type ${product.type}`);
    }
};
```

## What happens if later on, we introduce a new product type?

**Option 1** is pretty bad, there is nothing set in place to alert us that some code needs to be updated. In cases like this we have to start hunting `product.type` all around. Because of the hight frequency of this kind of conditional logic this is the root of many bugs.

**Option 2** and **3** make it a bit easier by throwing an error that will (hopefully) be caught during development as we implement the happy path. There is still a chance that a non happy path stays outdated (even more if the type is used for more than one application).

## Can we do better?

Ideally, we want to set some restriction around each use of this discriminant logic so that a new possible value will trigger a type error anywhere the value is being conditionally tested.

We can archive this in TypeScript using an exhaustive switch like this:

### Option 4: Uses a an exhaustive switch.

```typescript
const assertUnreachable = (value: never): never => {
    throw new Error(`No such case in exhaustive switch: ${value}`);
}

const calculateFare4 = (product: Product) => {
    switch (product.type) {
        case 'RIDE': {
            const rideFare = 0; // API call to get the fare.
            return calculateRideFare(product, rideFare);
        }
        case 'FOOD_DELIVERY': {
            const deliveryFare = 0; // API call to get the fare.
            return calculateDeliveryFare(product, deliveryFare);    
        }
        case 'ITEM_DELIVERY': {
            const deliveryFare = 0; // API call to get the fare.
            return calculateDeliveryFare2(product, deliveryFare);            
        }
        default:
            return assertUnreachable(product.type);
    }
};
```

When a new `type` is added TypeScript will complain everywhere and we can easily add new logic to handle the new product type. I was not able to do something similar when using FlowJS.

Another nice benefit of consistently using switch for these cases is that we can easily group logic that requires the same handling:

```typescript
const calculateFare4 = (product: Product) => {
    switch (product.type) {
        case 'RIDE': {
            const rideFare = 0; // API call to get the fare.
            return calculateRideFare(product, rideFare);
        }
        case 'FOOD_DELIVERY':
        case 'ITEM_DELIVERY': {
            const deliveryFare = 0; // API call to get the fare.
            return calculateDeliveryFare(product, deliveryFare);    
        }
        default:
            return assertUnreachable(product.type);
    }
};
```

> You can read more about the `never` type [here](https://www.typescriptlang.org/docs/handbook/basic-types.html#never)

[TypeScript Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgwgHgCoAUBOB7MBnAfFAXigAoxMcAuKVc7ASkPwDcMBLAEwG4Aob0SKOgzsArgGNgScNCIByAEoBJACIBRWVAA+UWTADye5QH01AGUUA1VfICaG7bMVJVAWROrzV2-Z0BBWTx80oKYohKEUADe3FCxUPwQVEJhktI8AL6BCSFY2BHRcVBkwuLASaGlGYEA9NVQemDArBgAdlAAjFQAqtgQeRAANr1QYgMAhiK9AHS8Yq3YwCNjA2Ii48AQMGNoEO0RpBUS5SUSDAT4BXGsAGYkxSlT2QTPOkpqsgyXhbFzLQtQaA4m22MigAAZOFBalBfChFEsBgN4hgoABzCCLYAAC2g1xBM2+cR2wBEaDaYmWq3WEHkQK2OwOJ2AABoAXSQXQeIV0lBBsMbndDsBHsFnnJ9IZ3J5rHZPjFCSN5ot2INWEwIGgQPTQRCoXVYfCKYjkWiMfEcVA8TsCQriaTyZS1mMNspVerNdrGSlWSqBmqNVqOVy4jy+dAvt9fv9ff6PSCIrroQaEUjgCj0ZiLVaIDbCXayQiqc6IK6-e7AzsAExe0o+t0B7Wc+WxdLcTK8aENJqtKCV7q9PKtAYgKCKGBQBbFgC2EBawDyYxa7HNmAA7tgZtwo4sjUWNtrK-t7qVjikzhdm1ABTWJCKBGLXip1HKFYq-otASrtQnIUm4SmTQzc1cXxS9CnzB0VidDZaS-EEbxZNk4J2JtuV5IZoGvY9byeF5dAMYwzEsGUPiiMC4m3KAY3Lb8iETfV-yNVN0zNbEQOtcjYggwtoJLes4wZbDEOohsg0vUMMKvW4ELvGQ8KcVwpWI7wXwVSiRIEnVfwYw1lmY01M3YnNOIBDF7R46lS1jCsIGrIS6zLUSUODFteEKbE1ygFoIFXKBVDQTA0GIAADLoWixRd2AGCBlyE+JggAEkiITZPSYKm3bbhO0aZo2gAZn7PooDGCdV1YYAxCxYqlyvKdinVPIdjGdgxgAI1YP1QE3Sjd147U8qPIVT1Kc8yMKbAyoqqqZISVTCQpYYFCfWQqAjV9KM-YEdh-PUYUYvTANYrNQNfcCzILXrqVgraIAQ1lNsbFzvlbdaxkWiVCI8ZS7FWkzCnU-ibJ2v9dONNMDOAy0TtOrjzsgvc+MczS7qowHHsKEyXrUt7oEcZw3CIrwfrGmG32jNH4zo7S9tB-SgLYqGONJ0ySQux1LIpqsUY0mzOWZzGTJVPE1jKP64g8jBfO83z-MCkKwoipdotioV4oEJKUoSNLUJDNsajqLtcqgAAWQqF2q3kAA8IsmJp1VK8rKu6pViuwXo0GAMKmsqtrov2JhlhERIvIgd06Cobz3UYEnYglqWfL8gKMCC4KADkUWwcQqoWzC2gga2JgWf0HamqgkoDgYg+1jJZhdy7i21Y3BqZYbTmjiMJsd6bNekObIxxx93l+5mNvZbaqd25MmMOwzGeM5nuPrmCx9u+ykJunXCSx+aB-wyVCZI4fSYBpGgYnkGAPB+njqZ0nF-Z4srJo+C1559G4gF17FoUgmvqJlaY6nRPtZWi4JqZTwOlfI6RlcynXvlBDmp8Dzc05hAPmpNP4KiFhMAYosF5w1du7T2LRvYRVatFGavcnqtkytlbsbRjZjCoAAcUwCIHAIxxiTCKtiZ0pkACOIhWDbWwGMGcUBFZRQ1M7d8hCNTENIb7UExAK5BwjqHDU4cQ5R3OIAuOIcZZJxTunCcWclj8jzgXW2xdO6lygOXQOEBq5tlrrIpeN0m5EAQq3YAo0O6TUqoKJksk+7-V3m8dQR8Yaj2QlpSe+0wYsVntmWBr54EI2up6NeD0xKvm3v3d6BElL-woCZHOOgf7FMPoA9aLs36UzAfE2mM9IYpLFrDVm8NeJPycqvIUDkQFBgxnkwWEBha4NKfgzpciPZewgGMH25C+nBNmtQvWQA)

## Other solutions

- [@typescript-eslint/switch-exhaustiveness-check](https://github.com/typescript-eslint/typescript-eslint/blob/9e0f6ddef7cd29f355f398c90f1986e51c4854f7/packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md#exhaustiveness-checking-in-switch-with-union-type-switch-exhaustiveness-check)
- Combine a `switch` with [TS Config - No implicit returns](https://www.typescriptlang.org/tsconfig#noImplicitReturns)

These solutions are less flexible and may not be available depending on the project configuration. For this reason, Option 4 is a very good pattern to standardize in the codebase.

**Comment by kahwee** [comment]
Curious why you chose `calculateDeliveryFare2` instead of using just `calculateDeliveryFare` in Option 1, 2 and 3.

**Comment by kahwee** [comment]
Good chance to highlight `never` is a keyword. I would have _never_ known if not for you emphasizing it in your presentation :D

**Comment by rareyesdev** [comment]
thanks @kahwee! I added more content to address your comments.

**Comment by rareyesdev** [comment]
Moved to https://www.rareyes.dev/blog/exhaustive-branch-checks
